### ISSUE TITLE
golang 1.18 errror

### ISSUE THREAD

**Issue by vearne** [Asphaltt/go-iproute2#1]
# github.com/Asphaltt/go-iproute2
../vendor/github.com/Asphaltt/go-iproute2/message.go:16:28: undefined: unix.SizeofIfInfomsg
../vendor/github.com/Asphaltt/go-iproute2/message.go:17:28: undefined: unix.SizeofIfAddrmsg
../vendor/github.com/Asphaltt/go-iproute2/message.go:18:28: undefined: unix.SizeofIfaCacheinfo
../vendor/github.com/Asphaltt/go-iproute2/message.go:19:28: undefined: unix.SizeofNdMsg
../vendor/github.com/Asphaltt/go-iproute2/message.go:20:28: undefined: unix.SizeofRtMsg
../vendor/github.com/Asphaltt/go-iproute2/message.go:88:17: undefined: unix.NdMsg
../vendor/github.com/Asphaltt/go-iproute2/message.go:118:21: undefined: unix.IfInfomsg
../vendor/github.com/Asphaltt/go-iproute2/message.go:140:21: undefined: unix.IfAddrmsg
../vendor/github.com/Asphaltt/go-iproute2/message.go:162:24: undefined: unix.IfaCacheinfo
../vendor/github.com/Asphaltt/go-iproute2/message.go:184:17: undefined: unix.RtMsg
../vendor/github.com/Asphaltt/go-iproute2/message.go:20:28: too many errors

**Comment by Asphaltt** [comment]
Hello, which GOOS do you use? 

Currently, **go-iproute2** only support Linux.

**Comment by vearne** [comment]
ok， thank you all the same.
